import os
import json
from datetime import datetime
import joblib
from fastapi import FastAPI
from pydantic import BaseModel

# Initialize FastAPI application
app = FastAPI(
    title="Spam Classification API",
    description="A simple API for classifying messages as spam or ham.",
    version="1.0"
)

# Load saved Machine Learning model and TF-IDF vectorizer at API startup
# These files were generated by running train.py
MODEL_PATH = "models/spam_model.pkl"
VECTORIZER_PATH = "models/tfidf_vectorizer.pkl"
LOGS_PATH = "data/prediction_logs.json"

if os.path.exists(MODEL_PATH) and os.path.exists(VECTORIZER_PATH):
    model = joblib.load(MODEL_PATH)
    vectorizer = joblib.load(VECTORIZER_PATH)
    print("Model and Vectorizer successfully loaded.")
else:
    model = None
    vectorizer = None
    print("WARNING: Model files not found. Please run train.py first!")


# Request schema using Pydantic
class MessageRequest(BaseModel):
    message: str


# Helper function to log predictions into data/prediction_logs.json
def save_prediction(message: str, prediction: str, probability: float):
    """
    Saves API prediction details into a JSON file for monitoring purposes.
    """
    os.makedirs("data", exist_ok=True)
    
    # 1. Check if prediction log file exists, otherwise start with empty list
    if os.path.exists(LOGS_PATH):
        try:
            with open(LOGS_PATH, "r") as f:
                logs = json.load(f)
        except Exception:
            logs = []
    else:
        logs = []

    # 2. Create record with timestamp
    log_entry = {
        "message": message,
        "prediction": prediction,
        "probability": round(probability, 4),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    # 3. Append new prediction
    logs.append(log_entry)

    # 4. Save updated list back to JSON file
    with open(LOGS_PATH, "w") as f:
        json.dump(logs, f, indent=4)


# Root endpoint GET /
@app.get("/")
def read_root():
    return {"message": "Spam Classification API is running"}


# Prediction endpoint POST /predict
@app.post("/predict")
def predict_spam(request: MessageRequest):
    if model is None or vectorizer is None:
        return {"error": "Model files missing. Please run train.py first."}

    raw_message = request.message
    # Preprocess input message (lowercase and strip spaces)
    cleaned_message = raw_message.lower().strip()

    # Convert text message to TF-IDF numerical vector
    message_vector = vectorizer.transform([cleaned_message])

    # Predict class ('spam' or 'ham')
    prediction = model.predict(message_vector)[0]

    # Calculate prediction probabilities using predict_proba()
    probabilities = model.predict_proba(message_vector)[0]
    
    # Get index of predicted class to extract its exact probability score
    class_index = list(model.classes_).index(prediction)
    prob_score = float(probabilities[class_index])

    # Log prediction to JSON file
    save_prediction(raw_message, prediction, prob_score)

    # Return prediction result as JSON response
    return {
        "message": raw_message,
        "prediction": prediction,
        "probability": round(prob_score, 2)
    }
